using System.Collections.Generic;
using System.Linq;
using System.Text;
using TestsGenerator.Core.Abstractions;
using TestsGenerator.Core.Models;

namespace TestsGenerator.Core
{
    public class CodeGenerator : IGenerator
    {
        private readonly ParserService _parser;

        public CodeGenerator(ParserService parser)
        {
            _parser = parser;
        }

        public IEnumerable<GeneratedFile> Generate(string sourceCode)
        {
            var classes = _parser.Parse(sourceCode);
            return classes.Select(CreateTestFile);
        }

        private GeneratedFile CreateTestFile(ClassInfo classInfo)
        {
            var sb = new StringBuilder();

            sb.AppendLine("using System;");
            sb.AppendLine("using NUnit.Framework;");
            sb.AppendLine("using Moq;");
            sb.AppendLine();

            sb.AppendLine("namespace Tests");
            sb.AppendLine("{");
            sb.AppendLine($"    [TestFixture]");
            sb.AppendLine($"    public class {classInfo.Name}Tests");
            sb.AppendLine("    {");

            sb.AppendLine($"        private {classInfo.Name} _testClass;");
            foreach (var dep in classInfo.ConstructorDependencies)
            {
                var interfaceName = dep.TrimStart('I');
                sb.AppendLine($"        private Mock<{dep}> _{interfaceName.ToLower()};");
            }

            sb.AppendLine();
            sb.AppendLine("        [SetUp]");
            sb.AppendLine("        public void SetUp()");
            sb.AppendLine("        {");
            foreach (var dep in classInfo.ConstructorDependencies)
            {
                var interfaceName = dep.TrimStart('I');
                sb.AppendLine($"            _{interfaceName.ToLower()} = new Mock<{dep}>();");
            }

            var constructorArgs = string.Join(", ", classInfo.ConstructorDependencies.Select(d => $"_{d.TrimStart('I').ToLower()}.Object"));
            sb.AppendLine($"            _testClass = new {classInfo.Name}({constructorArgs});");
            sb.AppendLine("        }");

            foreach (var method in classInfo.Methods)
            {
                sb.AppendLine();
                sb.AppendLine("        [Test]");
                sb.AppendLine($"        public void {method.Name}_Test()");
                sb.AppendLine("        {");
                sb.AppendLine("            // Arrange");
                if (method.ReturnType != "void")
                {
                    sb.AppendLine($"            {method.ReturnType} expected = default({method.ReturnType});");
                }

                sb.AppendLine();
                sb.AppendLine("            // Act");
                var call = $"_testClass.{method.Name}();";
                if (method.ReturnType == "void") sb.AppendLine($"            {call}");
                else sb.AppendLine($"            var actual = {call}");

                sb.AppendLine();
                sb.AppendLine("            // Assert");
                if (method.ReturnType != "void")
                {
                    sb.AppendLine("            Assert.Fail(\"Autogenerated test\");");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return new GeneratedFile($"{classInfo.Name}Tests.cs", sb.ToString());
        }
    }
}