using Xunit;
using TestsGenerator.Core;
using TestsGenerator.Core.Models;
using System.Collections.Generic;
using System.Linq;

namespace TestsGenerator.Tests
{
    public class CodeGeneratorTests
    {
        [Fact]
        public void Generate_ShouldIncludeNUnitAndMoqAttributes()
        {
            var parser = new ParserService();
            var generator = new CodeGenerator(parser);
            string sourceCode = "public class Simple { public void Method() {} }";

            var files = generator.Generate(sourceCode).ToList();
            var content = files[0].Content;

            Assert.Contains("[TestFixture]", content);
            Assert.Contains("[Test]", content);
            Assert.Contains("using Moq;", content);
        }

        [Fact]
        public void Generate_ShouldCreateMocksForInterfaces()
        {
            var parser = new ParserService();
            var generator = new CodeGenerator(parser);
            string sourceCode = "public class Bar { public Bar(ITracer tracer) {} }";

            var files = generator.Generate(sourceCode).ToList();
            var content = files[0].Content;

            Assert.Contains("private Mock<ITracer> _tracer;", content);
            Assert.Contains("_tracer = new Mock<ITracer>();", content);
            Assert.Contains("new Bar(_tracer.Object)", content);
        }

        [Fact]
        public void Generate_ShouldContainRequiredSectionsAndFail()
        {
            var parser = new ParserService();
            var generator = new CodeGenerator(parser);
            string sourceCode = "public class Foo { public int GetVal() => 10; }";

            var files = generator.Generate(sourceCode).ToList();
            var content = files[0].Content;

            Assert.Contains("// Arrange", content);
            Assert.Contains("// Act", content);
            Assert.Contains("// Assert", content);
            Assert.Contains("Assert.Fail(\"Autogenerated test\");", content);
        }
    }
}